# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/ota/layout/ota_layout.klay.gds
load ota_layout
select top cell
flatten ota_layout_flat
load ota_layout_flat
cellname delete ota_layout -noprompt
cellname rename ota_layout_flat ota_layout
select top cell
extract path /foss/designs/ota/pex/output/ota_layout__ota_layout/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/ota/pex/output/ota_layout__ota_layout/magic_CC -o /foss/designs/ota/pex/output/ota_layout__ota_layout/magic_CC/ota_layout.pex.spice
quit -noprompt