//file created by AOUALI Aymen in 14 feb 2026 at 5 PM
`timescale 1ns/1ps
module serializer_fake_adc (
    input           RESET       ,
    input           CLK         ,
    input           EN          ,   // try to always connect this enable pin to VDD
    input           ADC_IN      ,
    input           ADC_VALID   ,
    input           READY_IN    ,
    output          VALID_OUT   ,
    output  [9:0]   DATA_OUT    
);

    /*parameters begin*/
    /*parameters end*/
                
    /*signals begin*/
    reg [9:0]   sipo_flip_flops ; // flip flops of the entire register.
    wire[9:0]   data_out        ; // dataout from the skid buffer.
    wire        valid_out       ; // generated by the skid buffer.
    /*signals end*/
                
    /*instantiation begin*/
    skid_buffer #(   
        .DWIDTH (10) ) 
    skid(
    .clk        (CLK)               ,               // Clock
    .rst        (RESET)             ,               // Active-high synchronous reset
   
   // Input Interface (Upstream pipeline IF)  
    .data_in    (sipo_flip_flops)   ,           // Data in
    .valid_in   (ADC_VALID)         ,           // Data in valid
    .ready_out  ()                  ,           // Ready out: in our case it's note connected. (unused signal)
   
   // Output Interface (Downstream pipeline IF)
    .data_out   (data_out)          ,            // Data out
    .valid_out  (valid_out)         ,            // Data out valid
    .ready_in   (READY_IN)      
    );
    /*instantiation end*/
                
    /*discription begin*/
    // sipo register
    always @(posedge CLK ) begin
        if (RESET) begin
            sipo_flip_flops <= 10'b0;
        end else if (EN) begin
        sipo_flip_flops <= {sipo_flip_flops[8:0], ADC_IN};
        end    
    end
    /*discription end*/
                
    /*output assignment begin*/
    assign  VALID_OUT   = valid_out ;   
    assign  DATA_OUT    = data_out  ;
    /*output assignment end*/
    
endmodule


