# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/ota/layout/ota_layout.klay.gds
load ota_layout
select top cell
flatten ota_layout_flat
load ota_layout_flat
cellname delete ota_layout -noprompt
cellname rename ota_layout_flat ota_layout
select top cell
extract path /foss/designs/ota/pex/output/ota_layout__ota_layout/magic_R
extract no capacitance
extract no coupling
extract all
ext2sim labels on
ext2sim -p /foss/designs/ota/pex/output/ota_layout__ota_layout/magic_R
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/ota/pex/output/ota_layout__ota_layout/magic_R -o /foss/designs/ota/pex/output/ota_layout__ota_layout/magic_R/ota_layout.pex.spice
quit -noprompt
