# Generated by kpex 0.3.8
crashbackups stop
drc off
gds read /foss/designs/bgr_ip/bgr_ip.klay.gds
load bgr_ip
select top cell
flatten bgr_ip_flat
load bgr_ip_flat
cellname delete bgr_ip -noprompt
cellname rename bgr_ip_flat bgr_ip
select top cell
extract path /foss/designs/bgr_ip/pex/output/bgr_ip__bgr_ip/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/bgr_ip/pex/output/bgr_ip__bgr_ip/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/bgr_ip/pex/output/bgr_ip__bgr_ip/magic_RC -o /foss/designs/bgr_ip/pex/output/bgr_ip__bgr_ip/magic_RC/bgr_ip.pex.spice
quit -noprompt
